# docker-compose.yml
# 2019-2-25
# Author:  Daniel Nicolas Gisolfi

version: "2"
services:
  ghl:
    build: .
    ports:
      - "3000:3000"
    container_name: ghl
    depends_on:
      - db
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: groundhoglog
      MYSQL_USER: GHL
      MYSQL_PASSWORD: Gr0undH0gL0g
      MYSQL_RANDOM_ROOT_PASSWORD: pwgen
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql

  